### ISSUE TITLE
Glances Options and results need validation and exception handling

### ISSUE THREAD

**Issue by kevinsheng93** [jalalmostafa/SciTS#1]
I configured the *.config files in the WORKLOADS directory. But the errors still occur "System.Exception: Null or empty app settings val for key=SensorNumber" and "System.Exception: Null or empty app settings val for key=MetricsCSVPath". How sholud I resove them?

**Comment by jalalmostafa** [comment]
Have you specified `MetricsCSVPath` in the workload definition file? This is the name of the CSV file where the performance metrics are stored.

**Comment by kevinsheng93** [comment]
yes, i used the default configuration, which is "Metrics.csv".

**Comment by jalalmostafa** [comment]
The exception is thrown here

https://github.com/jalalmostafa/SciTS/blob/721da078e9a6d1c295179ca0131b7a31dc283768/BenchmarkTool/Config.cs#L71

Either the argument name is mistyped or the valid is null or empty.
Did you rename the file to `App.config` (case-sensitive)?

Otherwise, I need a way to reproduce the error. e.g. what system are you using? dotnet SDK version? and the steps you follow to reproduce the bug.

**Comment by kevinsheng93** [comment]
Yes, the error is caused by the file App.config. I forgot to rename it.
However, there comes another error.
2022-08-08 11:02:57.756 +08:00 [ERR] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert null to 'int' because it is a non-nullable value type
   at RestSharp.RestClientExtensions.ThrowIfError(IRestResponse response)
   at RestSharp.RestClientExtensions.GetAsync[T](IRestClient client, IRestRequest request, CancellationToken cancellationToken)
   at BenchmarkTool.System.GlancesMonitor.GetAllAsync(Int32 pid, String nic, String disk) in C:\Users\s00589984\PycharmProjects\SciTS\BenchmarkTool\System\GlancesMonitor.cs:line 69
   at BenchmarkTool.System.GlancesStarter.Monitor() in C:\Users\s00589984\PycharmProjects\SciTS\BenchmarkTool\System\GlancesStarter.cs:line 50.
Could you give me some advice? thank you

**Comment by kevinsheng93** [comment]
Yes, the error is caused by the file App.config. I forgot to rename it.
However, there comes another error.
2022-08-08 11:02:57.756 +08:00 [ERR] Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert null to 'int' because it is a non-nullable value type
at RestSharp.RestClientExtensions.ThrowIfError(IRestResponse response)
at RestSharp.RestClientExtensions.GetAsync[T](IRestClient client, IRestRequest request, CancellationToken cancellationToken)
at BenchmarkTool.System.GlancesMonitor.GetAllAsync(Int32 pid, String nic, String disk) in C:\Users\xxx\PycharmProjects\SciTS\BenchmarkTool\System\GlancesMonitor.cs:line 69
at BenchmarkTool.System.GlancesStarter.Monitor() in C:\Users\xxx\PycharmProjects\SciTS\BenchmarkTool\System\GlancesStarter.cs:line 50.
Could you give me some advice? thank you

**Comment by jalalmostafa** [comment]
This is a bug, Please enter valid values in `Glances***` options.

```xml
<add key="GlancesDatabasePid" value="1" />
<add key="GlancesPeriod" value="1" />
<add key="GlancesOutput" value="Glances.csv"/>
<add key="GlancesNIC" value="enp9s0" />
<add key="GlancesDisk" value="sda1" />
```
